# Data Preprocessing

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### 1.1 Loading the Dataset

#### 1.1.1 Reloading the Dataset

In [56]:
# Reloading the dataset and displaying in the desired format
df_basic = pd.read_csv('patient.csv')
df_basic.head(6)

,encounter_id,patient_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,icu_admit_source,...,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,apache_3j_bodysystem,apache_2_bodysystem,Unnamed: 83,hospital_death
0,66154,25312,118,68.0,22.73,0,Caucasian,M,180.3,Floor,...,1.0,0.0,0.0,0.0,0.0,0.0,Sepsis,Cardiovascular,NaN,0
1,114252,59342,81,77.0,27.42,0,Caucasian,F,160.0,Floor,...,1.0,0.0,0.0,0.0,0.0,0.0,Respiratory,Respiratory,NaN,0
2,119783,50777,118,25.0,31.95,0,Caucasian,F,172.7,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic,NaN,0
3,79267,46918,118,81.0,22.64,1,Caucasian,F,165.1,Operating Room / Recovery,...,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular,NaN,0
4,92056,34377,33,19.0,NaN,0,Caucasian,M,188.0,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,Trauma,Trauma,NaN,0
5,33181,74489,83,67.0,27.56,0,Caucasian,M,190.5,Accident & Emergency,...,1.0,0.0,0.0,0.0,0.0,0.0,Neurological,Neurologic,NaN,0

#### 1.1.2 Removing duplicate rows and dropping completely empty columns

In [58]:
df_basic = df_basic.drop_duplicates()

df_basic = df_basic.dropna(axis=1, how='all')

#### 1.1.3 Checking the updated structure

In [59]:
df_basic.head(6)

,encounter_id,patient_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,icu_admit_source,...,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,apache_3j_bodysystem,apache_2_bodysystem,hospital_death
0,66154,25312,118,68.0,22.73,0,Caucasian,M,180.3,Floor,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Sepsis,Cardiovascular,0
1,114252,59342,81,77.0,27.42,0,Caucasian,F,160.0,Floor,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Respiratory,Respiratory,0
2,119783,50777,118,25.0,31.95,0,Caucasian,F,172.7,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic,0
3,79267,46918,118,81.0,22.64,1,Caucasian,F,165.1,Operating Room / Recovery,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular,0
4,92056,34377,33,19.0,NaN,0,Caucasian,M,188.0,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Trauma,Trauma,0
5,33181,74489,83,67.0,27.56,0,Caucasian,M,190.5,Accident & Emergency,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Neurological,Neurologic,0

### 1.2 Missing Value Analysis

#### 1.2.1 Calculate Missing Values and their Percentages

In [60]:
missing_values = df_basic.isnull().sum()
missing_percentage = (missing_values / len(df_basic)) * 100

# Create a missing data report
missing_data_report = pd.DataFrame({
    "Column": df_basic.columns,
    "Missing Values": missing_values,
    "Missing Percentage (%)": missing_percentage
}).sort_values(by="Missing Percentage (%)", ascending=False)

# Display columns with missing values
missing_data_report[missing_data_report["Missing Values"] > 0]

,Column,Missing Values,Missing Percentage (%)
d1_potassium_max,d1_potassium_max,9585,10.451081
d1_potassium_min,d1_potassium_min,9585,10.451081
h1_mbp_noninvasive_max,h1_mbp_noninvasive_max,9084,9.904812
h1_mbp_noninvasive_min,h1_mbp_noninvasive_min,9084,9.904812
apache_4a_icu_death_prob,apache_4a_icu_death_prob,7947,8.665075
...,...,...,...
d1_sysbp_min,d1_sysbp_min,159,0.173367
d1_heartrate_max,d1_heartrate_max,145,0.158102
d1_heartrate_min,d1_heartrate_min,145,0.158102
icu_admit_source,icu_admit_source,112,0.122120
gender,gender,25,0.027259

#### 1.2.2 Handling Missing Values

In [61]:
# Strategy 1: Drop columns with more than 50% missing values
threshold = 50  # Percentage threshold for dropping columns
columns_to_drop = missing_data_report[missing_data_report["Missing Percentage (%)"] > threshold]["Column"]
df_basic = df_basic.drop(columns=columns_to_drop)

# Strategy 2: Impute missing values for numeric columns with mean
numeric_columns = df_basic.select_dtypes(include=["float64", "int64"]).columns
df_basic[numeric_columns] = df_basic[numeric_columns].apply(lambda col: col.fillna(col.mean()))

# Strategy 3: Impute missing values for categorical columns with mode
categorical_columns = df_basic.select_dtypes(include=["object"]).columns
df_basic[categorical_columns] = df_basic[categorical_columns].apply(lambda col: col.fillna(col.mode()[0]))

# Check for remaining missing values
remaining_missing_values = df_basic.isnull().sum().sum()

# Display the updated dataset structure and check if missing values remain
df_basic.info(), remaining_missing_values

<class 'pandas.core.frame.DataFrame'>
Int64Index: 91713 entries, 0 to 91712
Data columns (total 84 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   encounter_id                   91713 non-null  int64
 1   patient_id                     91713 non-null  int64
 2   hospital_id                    91713 non-null  int64
 3   age                            91713 non-null  float64
 4   bmi                            91713 non-null  float64
 5   elective_surgery               91713 non-null  int64
 6   ethnicity                      91713 non-null  object
 7   gender                         91713 non-null  object
 8   height                         91713 non-null  float64
 9   icu_admit_source               91713 non-null  object
 10  icu_id                         91713 non-null  int64
 11  icu_stay_type                  91713 non-null  object
 12  icu_type                       91713 non-null  object
 13  pre_icu_los_days               91713 non-null  float64
 14  weight                         91713 non-null  float64
 15  apache_2_diagnosis             91713 non-null  float64
 16  apache_3j_diagnosis            91713 non-null  float64
 17  apache_post_operative          91713 non-null  int64
 18  arf_apache                     91713 non-null  float64
 19  gcs_eyes_apache                91713 non-null  float64
 20  gcs_motor_apache               91713 non-null  float64
 21  gcs_unable_apache              91713 non-null  float64
 22  gcs_verbal_apache              91713 non-null  float64
 23  heart_rate_apache              91713 non-null  float64
 24  intubated_apache               91713 non-null  float64
 25  map_apache                     91713 non-null  float64
 26  resprate_apache                91713 non-null  float64
 27  temp_apache                    91713 non-null  float64
 28  ventilated_apache              91713 non-null  float64
 29  d1_diasbp_max                  91713 non-null  float64
 30  d1_diasbp_min                  91713 non-null  float64
 31  d1_diasbp_noninvasive_max      91713 non-null  float64
 32  d1_diasbp_noninvasive_min      91713 non-null  float64
 33  d1_heartrate_max               91713 non-null  float64
 34  d1_heartrate_min               91713 non-null  float64
 35  d1_mbp_max                     91713 non-null  float64
 36  d1_mbp_min                     91713 non-null  float64
 37  d1_mbp_noninvasive_max         91713 non-null  float64
 38  d1_mbp_noninvasive_min         91713 non-null  float64
 39  d1_resprate_max                91713 non-null  float64
 40  d1_resprate_min                91713 non-null  float64
 41  d1_spo2_max                    91713 non-null  float64
 42  d1_spo2_min                    91713 non-null  float64
 43  d1_sysbp_max                   91713 non-null  float64
 44  d1_sysbp_min                   91713 non-null  float64
 45  d1_sysbp_noninvasive_max       91713 non-null  float64
 46  d1_sysbp_noninvasive_min       91713 non-null  float64
 47  d1_temp_max                    91713 non-null  float64
 48  d1_temp_min                    91713 non-null  float64
 49  h1_diasbp_max                  91713 non-null  float64
 50  h1_diasbp_min                  91713 non-null  float64
 51  h1_diasbp_noninvasive_max      91713 non-null  float64
 52  h1_diasbp_noninvasive_min      91713 non-null  float64
 53  h1_heartrate_max               91713 non-null  float64
 54  h1_heartrate_min               91713 non-null  float64
 55  h1_mbp_max                     91713 non-null  float64
 56  h1_mbp_min                     91713 non-null  float64
 57  h1_mbp_noninvasive_max         91713 non-null  float64
 58  h1_mbp_noninvasive_min         91713 non-null  float64
 59  h1_resprate_max                91713 non-null  float64
 60  h1_resprate_min                91713 non-null  float64
 61  h1_spo2_max                    91713 non-null  float64
 62  h1_spo2_min                    91713 non-null  float64
 63  h1_sysbp_max                   91713 non-null  float64
 64  h1_sysbp_min                   91713 non-null  float64
 65  h1_sysbp_noninvasive_max       91713 non-null  float64
 66  h1_sysbp_noninvasive_min       91713 non-null  float64
 67  d1_glucose_max                 91713 non-null  float64
 68  d1_glucose_min                 91713 non-null  float64
 69  d1_potassium_max               91713 non-null  float64
 70  d1_potassium_min               91713 non-null  float64
 71  apache_4a_hospital_death_prob  91713 non-null  float64
 72  apache_4a_icu_death_prob       91713 non-null  float64
 73  aids                           91713 non-null  float64
 74  cirrhosis                      91713 non-null  float64
 75  diabetes_mellitus              91713 non-null  float64
 76  hepatic_failure                91713 non-null  float64
 77  immunosuppression              91713 non-null  float64
 78  leukemia                       91713 non-null  float64
 79  lymphoma                       91713 non-null  float64
 80  solid_tumor_with_metastasis    91713 non-null  float64
 81  apache_3j_bodysystem           91713 non-null  object
 82  apache_2_bodysystem            91713 non-null  object
 83  hospital_death                 91713 non-null  int64
dtypes: float64(70), int64(7), object(7)
memory usage: 59.5+ MB

(None, 0)

### 1.3 Identifying and removing non-relevant features

In [62]:
# Remove non-related columns based on domain knowledge
non_related_columns = ['encounter_id', 'patient_id', 'hospital_id', 'Unnamed: 83', 'icu_id']
df_basic = df_basic.drop(columns=non_related_columns, errors='ignore')